name: Build & Release Wheel

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release tag (e.g. v0.22.29-fork)'
        required: true

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Install build dependencies
      run: pip install build

    - name: Build wheel
      run: python -m build --wheel

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ github.event.inputs.tag }}
        files: dist/*.whl
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
