name: Build Dev Wheel

on:
  workflow_dispatch:
    inputs:
      label:
        description: 'Label (e.g. dev, debug, feature-x)'
        required: true
        default: 'dev'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Install build dependencies
      run: pip install build

    - name: Build wheel
      run: |
        pip install build
        python -m build --wheel
        echo "WHEEL_FILENAME=$(ls dist/*.whl)" >> $GITHUB_ENV

    - name: Rename wheel with label
      shell: python
      run: |
        import os
        import glob
        import shutil

        wheel = glob.glob('dist/*.whl')[0]
        parts = wheel.split('-')
        parts[1] = parts[1] + '.dev'
        new_name = '-'.join(parts)
        shutil.move(wheel, new_name)
        print(f'Renamed: {new_name}')
      
    - name: Upload wheel artifact
      uses: actions/upload-artifact@v4
      with:
          name: pyxcp-dev-wheel
          path: dist/*.whl
      